BASE_URL = "https://www.saucedemo.com"
invalid_login_xlsx = "data/invalid_login.xlsx"
valid_login_xlsx = "data/valid_login.xlsx"

USERNAME_ID = "user-name"
PASSWORD_ID = "password"
LOGIN_BUTTON = "login-button"
ERROR_MESSAGE_XPATH = "//*[@id='login_button_container']/div/form/div[3]/h3"
USERNAME_PASSWORD_INVALID = "Epic sadface: Username and password do not match any user in this"
EMPTY_INVALID = "Epic sadface: Username is required"
INVENTORY_ITEM = "inventory_item"
SHOPPIND_XPATH = "//*[@id='shopping_cart_container']"
CHECKOUT = "checkout"
FIRST_NAME = "first-name"
LAST_NAME = "last-name"
POSTAL_CODE = "postal-code"
CONTINUE = "continue"
CHECKOUT_ERROR_XPATH = "//*[@id='checkout_info_container']/div/form/div[1]/div[4]/h3"